# Generated by Django 5.2.8 on 2025-12-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonCode",
            fields=[
                (
                    "common_code",
                    models.CharField(
                        db_column="common_code",
                        help_text="공통 코드 (약자+숫자3자리, 예: ABC001)",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        db_column="common_name",
                        help_text="공통 코드 그룹명",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="description", help_text="설명", null=True
                    ),
                ),
                (
                    "use_yn",
                    models.CharField(
                        db_column="use_yn",
                        default="Y",
                        help_text="사용 여부 (Y/N)",
                        max_length=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "created_id",
                    models.CharField(
                        db_column="created_id", help_text="생성자 ID", max_length=60
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "updated_id",
                    models.CharField(
                        db_column="updated_id", help_text="수정자 ID", max_length=60
                    ),
                ),
            ],
            options={
                "verbose_name": "공통 코드 그룹",
                "verbose_name_plural": "공통 코드 그룹들",
                "db_table": "tc_common",
                "ordering": ["common_code"],
                "indexes": [
                    models.Index(fields=["use_yn"], name="tc_common_use_yn_0ef7ac_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CommonCodeItem",
            fields=[
                (
                    "common_item_code",
                    models.CharField(
                        db_column="common_item_code",
                        help_text="공통 코드 항목 코드 (약자+숫자3자리, 예: ABC001)",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "common_item_name",
                    models.CharField(
                        db_column="common_item_name",
                        help_text="공통 코드 항목명",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="description", help_text="설명", null=True
                    ),
                ),
                (
                    "use_yn",
                    models.CharField(
                        db_column="use_yn",
                        default="Y",
                        help_text="사용 여부 (Y/N)",
                        max_length=1,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_column="sort_order", default=0, help_text="정렬 순서"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "created_id",
                    models.CharField(
                        db_column="created_id", help_text="생성자 ID", max_length=60
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "updated_id",
                    models.CharField(
                        db_column="updated_id", help_text="수정자 ID", max_length=60
                    ),
                ),
                (
                    "common_code",
                    models.ForeignKey(
                        db_column="common_code",
                        help_text="공통 코드 그룹",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="codes.commoncode",
                    ),
                ),
            ],
            options={
                "verbose_name": "공통 코드 항목",
                "verbose_name_plural": "공통 코드 항목들",
                "db_table": "tc_common_item",
                "ordering": ["common_code", "sort_order", "common_item_code"],
                "indexes": [
                    models.Index(
                        fields=["common_code", "use_yn"],
                        name="tc_common_i_common__e8abb1_idx",
                    ),
                    models.Index(
                        fields=["sort_order"], name="tc_common_i_sort_or_d8b033_idx"
                    ),
                ],
            },
        ),
    ]
