# Generated by Django 5.2.8 on 2025-12-14 09:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                        verbose_name="사용자 ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="회사/소속"
                    ),
                ),
                (
                    "img_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="프로필 이미지 URL",
                    ),
                ),
                (
                    "join_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="가입일"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 로그인"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "활성"),
                            ("D", "비활성"),
                            ("S", "정지"),
                            ("A", "관리자"),
                        ],
                        default="E",
                        max_length=1,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="관리자 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "zs_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "settings_sid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="설정 ID"
                    ),
                ),
                (
                    "notifications",
                    models.CharField(
                        choices=[("Y", "예"), ("N", "아니오")],
                        default="Y",
                        max_length=1,
                        verbose_name="알림",
                    ),
                ),
                (
                    "email_alerts",
                    models.CharField(
                        choices=[("Y", "예"), ("N", "아니오")],
                        default="Y",
                        max_length=1,
                        verbose_name="이메일 알림",
                    ),
                ),
                (
                    "dark_mode",
                    models.CharField(
                        choices=[("Y", "예"), ("N", "아니오")],
                        default="N",
                        max_length=1,
                        verbose_name="다크 모드",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ko", "한국어"),
                            ("en", "English"),
                            ("ja", "日本語"),
                            ("zh", "中文"),
                        ],
                        default="ko",
                        max_length=10,
                        verbose_name="언어",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 설정",
                "verbose_name_plural": "사용자 설정 목록",
                "db_table": "zs_user_settings",
            },
        ),
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                (
                    "linked_account_sid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="연동 계정 ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("kakao", "Kakao"),
                            ("naver", "Naver"),
                        ],
                        help_text="google, github, kakao, naver 등",
                        max_length=50,
                        verbose_name="제공자",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        help_text="OAuth 제공자에서의 고유 사용자 ID",
                        max_length=255,
                        verbose_name="제공자 사용자 ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="액세스 토큰",
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="리프레시 토큰",
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="토큰 만료 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "연동 계정",
                "verbose_name_plural": "연동 계정 목록",
                "db_table": "zs_linked_account",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uk_provider_user"
                    )
                ],
            },
        ),
    ]
