# Generated by Django 5.2.8 on 2026-01-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedaccount",
            name="scope",
            field=models.TextField(
                blank=True,
                help_text="OAuth 제공자에서 부여된 권한 목록 (공백으로 구분)",
                null=True,
                verbose_name="권한 범위",
            ),
        ),
    ]
