# Generated by Django 5.2.8 on 2026-01-03 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_linkedaccount_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, verbose_name='경로')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 메서드')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 활동 로그',
                'verbose_name_plural': '사용자 활동 로그 목록',
                'db_table': 'zh_user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
