# Generated by Django 5.2.8 on 2026-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_useractivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="notes_view_mode",
            field=models.CharField(
                choices=[("card", "카드 보기"), ("table", "테이블 보기")],
                default="card",
                max_length=10,
                verbose_name="노트 보기 모드",
            ),
        ),
    ]
