# Generated by Django 5.2.9 on 2025-12-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_sid', models.AutoField(db_column='chat_sid', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=500, null=True)),
                ('preview', models.TextField(blank=True, db_column='preview', null=True)),
                ('status', models.CharField(choices=[('E', '사용'), ('D', 'Disabled'), ('R', 'Removed')], db_column='status', default='E', max_length=1)),
                ('pinned', models.CharField(db_column='pinned', default='N', max_length=1)),
                ('archived', models.CharField(db_column='archived', default='N', max_length=1)),
                ('filter_type', models.CharField(blank=True, db_column='filter_type', max_length=50, null=True)),
                ('auto_mode', models.CharField(db_column='auto_mode', default='Y', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_id', models.CharField(db_column='updated_id', max_length=60)),
            ],
            options={
                'verbose_name': '채팅',
                'verbose_name_plural': '채팅들',
                'db_table': 't_chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperGraph',
            fields=[
                ('graph_sid', models.AutoField(db_column='graph_sid', primary_key=True, serialize=False)),
                ('graph_title', models.CharField(blank=True, db_column='graph_title', max_length=255, null=True)),
                ('graph_description', models.TextField(blank=True, db_column='graph_description', null=True)),
                ('status', models.CharField(choices=[('E', '사용'), ('D', 'Disabled')], db_column='status', default='E', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('updated_id', models.CharField(blank=True, db_column='updated_id', max_length=60, null=True)),
            ],
            options={
                'verbose_name': '논문 그래프',
                'verbose_name_plural': '논문 그래프들',
                'db_table': 't_paper_graph',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedQuestion',
            fields=[
                ('question_sid', models.AutoField(db_column='question_sid', primary_key=True, serialize=False)),
                ('question_text', models.CharField(db_column='question_text', max_length=500)),
                ('question_category', models.CharField(choices=[('P', '논문'), ('C', '임상'), ('T', '프로토콜'), ('S', '시뮬레이션'), ('R', '결과 해석')], db_column='question_category', max_length=1)),
                ('sort_order', models.IntegerField(db_column='sort_order', default=0)),
                ('status', models.CharField(choices=[('E', '사용'), ('D', 'Disabled'), ('R', 'Removed')], db_column='status', default='E', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': '추천 질문',
                'verbose_name_plural': '추천 질문들',
                'db_table': 't_recommended_question',
                'ordering': ['sort_order', 'question_sid'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_sid', models.AutoField(db_column='message_sid', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('U', 'User'), ('A', 'Assistant')], db_column='role', max_length=1)),
                ('content', models.TextField(db_column='content')),
                ('sort_order', models.IntegerField(db_column='sort_order')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('concept_graph', models.TextField(blank=True, db_column='concept_graph', null=True)),
                ('chat', models.ForeignKey(db_column='chat_sid', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'db_table': 't_chat_message',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageFeedback',
            fields=[
                ('feedback_sid', models.AutoField(db_column='feedback_sid', primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('L', '좋아요'), ('D', '싫어요'), ('I', '개선제안'), ('E', '오류신고'), ('O', '기타')], db_column='feedback_type', max_length=1)),
                ('rating', models.SmallIntegerField(blank=True, db_column='rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_id', models.CharField(db_column='updated_id', max_length=60)),
                ('message', models.ForeignKey(db_column='message_sid', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': '채팅 메시지 피드백',
                'verbose_name_plural': '채팅 메시지 피드백들',
                'db_table': 't_chat_message_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatReference',
            fields=[
                ('reference_sid', models.AutoField(db_column='reference_sid', primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('P', 'PubMed'), ('W', 'Web'), ('N', 'NIH'), ('T', 'PROTOCOL')], db_column='source', max_length=1)),
                ('badge', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], db_column='badge', max_length=1)),
                ('title', models.CharField(db_column='title', max_length=500)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('journal', models.CharField(choices=[('J', 'Journal'), ('B', 'Book'), ('R', 'Report'), ('P', 'Protocol')], db_column='journal', max_length=1)),
                ('link', models.CharField(blank=True, db_column='link', max_length=500, null=True)),
                ('ref_pubmed_id', models.CharField(blank=True, db_column='ref_pubmed_id', max_length=100, null=True)),
                ('ref_date', models.DateTimeField(blank=True, db_column='ref_date', null=True)),
                ('ref_authors', models.CharField(blank=True, db_column='ref_authors', max_length=500, null=True)),
                ('sort_order', models.IntegerField(db_column='sort_order', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('chat', models.ForeignKey(db_column='chat_sid', on_delete=django.db.models.deletion.CASCADE, related_name='references', to='chat.chat')),
                ('message', models.ForeignKey(blank=True, db_column='message_sid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': '채팅 참고 문헌',
                'verbose_name_plural': '채팅 참고 문헌들',
                'db_table': 't_chat_reference',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperEdge',
            fields=[
                ('edge_sid', models.AutoField(db_column='edge_sid', primary_key=True, serialize=False)),
                ('source_paper_id', models.CharField(db_column='source_paper_id', max_length=100)),
                ('target_paper_id', models.CharField(db_column='target_paper_id', max_length=100)),
                ('edge_size', models.IntegerField(db_column='edge_size', default=1)),
                ('edge_color', models.CharField(blank=True, db_column='edge_color', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('graph', models.ForeignKey(db_column='graph_sid', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='chat.papergraph')),
            ],
            options={
                'verbose_name': '논문 엣지',
                'verbose_name_plural': '논문 엣지들',
                'db_table': 't_paper_edge',
                'unique_together': {('graph', 'source_paper_id', 'target_paper_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessagePaperGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_column='sort_order', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('message', models.ForeignKey(db_column='message_sid', on_delete=django.db.models.deletion.CASCADE, related_name='paper_graphs', to='chat.chatmessage')),
                ('graph', models.ForeignKey(db_column='graph_sid', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.papergraph')),
            ],
            options={
                'verbose_name': '채팅 메시지 논문 그래프',
                'verbose_name_plural': '채팅 메시지 논문 그래프들',
                'db_table': 't_chat_message_paper_graph',
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('message', 'graph')},
            },
        ),
        migrations.CreateModel(
            name='PaperNode',
            fields=[
                ('node_sid', models.AutoField(db_column='node_sid', primary_key=True, serialize=False)),
                ('paper_id', models.CharField(db_column='paper_id', max_length=100)),
                ('paper_label', models.CharField(db_column='paper_label', max_length=255)),
                ('node_size', models.IntegerField(db_column='node_size', default=20)),
                ('node_color', models.CharField(blank=True, db_column='node_color', max_length=50, null=True)),
                ('x_position', models.DecimalField(blank=True, db_column='x_position', decimal_places=2, max_digits=10, null=True)),
                ('y_position', models.DecimalField(blank=True, db_column='y_position', decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('graph', models.ForeignKey(db_column='graph_sid', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chat.papergraph')),
            ],
            options={
                'verbose_name': '논문 노드',
                'verbose_name_plural': '논문 노드들',
                'db_table': 't_paper_node',
                'ordering': ['paper_id'],
                'unique_together': {('graph', 'paper_id')},
            },
        ),
    ]
