# Generated by Django 5.2.8 on 2025-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendedQuestion",
            fields=[
                (
                    "question_sid",
                    models.AutoField(
                        db_column="question_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "question_text",
                    models.CharField(db_column="question_text", max_length=500),
                ),
                (
                    "question_category",
                    models.CharField(
                        choices=[
                            ("P", "논문"),
                            ("C", "임상"),
                            ("T", "프로토콜"),
                            ("S", "시뮬레이션"),
                            ("R", "결과 해석"),
                        ],
                        db_column="question_category",
                        max_length=1,
                    ),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("E", "사용"), ("D", "Disabled"), ("R", "Removed")],
                        db_column="status",
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "verbose_name": "추천 질문",
                "verbose_name_plural": "추천 질문들",
                "db_table": "t_recommended_question",
                "ordering": ["sort_order", "question_sid"],
            },
        ),
    ]
