# Generated by Django 5.2.9 on 2025-12-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papergraph',
            name='updated_id',
        ),
    ]
