# Generated by Django 5.2.8 on 2025-12-14 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_chatmessage_chatmessagefeedback_chatreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperGraph",
            fields=[
                (
                    "graph_sid",
                    models.AutoField(
                        db_column="graph_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "graph_title",
                    models.CharField(
                        blank=True, db_column="graph_title", max_length=255, null=True
                    ),
                ),
                (
                    "graph_description",
                    models.TextField(
                        blank=True, db_column="graph_description", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("E", "사용"), ("D", "Disabled")],
                        db_column="status",
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
            ],
            options={
                "verbose_name": "논문 그래프",
                "verbose_name_plural": "논문 그래프들",
                "db_table": "t_paper_graph",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperEdge",
            fields=[
                (
                    "edge_sid",
                    models.AutoField(
                        db_column="edge_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_paper_id",
                    models.CharField(db_column="source_paper_id", max_length=100),
                ),
                (
                    "target_paper_id",
                    models.CharField(db_column="target_paper_id", max_length=100),
                ),
                ("edge_size", models.IntegerField(db_column="edge_size", default=1)),
                (
                    "edge_color",
                    models.CharField(
                        blank=True, db_column="edge_color", max_length=50, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        db_column="graph_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="chat.papergraph",
                    ),
                ),
            ],
            options={
                "verbose_name": "논문 엣지",
                "verbose_name_plural": "논문 엣지들",
                "db_table": "t_paper_edge",
                "unique_together": {("graph", "source_paper_id", "target_paper_id")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessagePaperGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.SmallIntegerField(db_column="sort_order", default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "message",
                    models.ForeignKey(
                        db_column="message_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_graphs",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        db_column="graph_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="chat.papergraph",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지 논문 그래프",
                "verbose_name_plural": "채팅 메시지 논문 그래프들",
                "db_table": "t_chat_message_paper_graph",
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("message", "graph")},
            },
        ),
        migrations.CreateModel(
            name="PaperNode",
            fields=[
                (
                    "node_sid",
                    models.AutoField(
                        db_column="node_sid", primary_key=True, serialize=False
                    ),
                ),
                ("paper_id", models.CharField(db_column="paper_id", max_length=100)),
                (
                    "paper_label",
                    models.CharField(db_column="paper_label", max_length=255),
                ),
                ("node_size", models.IntegerField(db_column="node_size", default=20)),
                (
                    "node_color",
                    models.CharField(
                        blank=True, db_column="node_color", max_length=50, null=True
                    ),
                ),
                (
                    "x_position",
                    models.DecimalField(
                        blank=True,
                        db_column="x_position",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "y_position",
                    models.DecimalField(
                        blank=True,
                        db_column="y_position",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "graph",
                    models.ForeignKey(
                        db_column="graph_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="chat.papergraph",
                    ),
                ),
            ],
            options={
                "verbose_name": "논문 노드",
                "verbose_name_plural": "논문 노드들",
                "db_table": "t_paper_node",
                "ordering": ["paper_id"],
                "unique_together": {("graph", "paper_id")},
            },
        ),
    ]
