# Generated by Django 5.2.8 on 2025-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_papergraph_paperedge_chatmessagepapergraph_papernode"),
    ]

    operations = [
        migrations.AddField(
            model_name="papergraph",
            name="updated_id",
            field=models.CharField(
                blank=True, db_column="updated_id", max_length=60, null=True
            ),
        ),
    ]
