# Generated by Django 5.2.8 on 2025-12-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_papergraph_updated_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="concept_graph",
            field=models.TextField(blank=True, db_column="concept_graph"),
        ),
    ]
