# Generated by Django 5.2.9 on 2025-12-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_migrate_pinned_to_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='pinned',
        ),
    ]
