# Generated by Django 5.2.9 on 2025-12-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatreference',
            options={'ordering': ['ref_id', 'created_at'], 'verbose_name': '채팅 참고 문헌', 'verbose_name_plural': '채팅 참고 문헌들'},
        ),
        migrations.RemoveField(
            model_name='chatreference',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='chatreference',
            name='ref_id',
            field=models.IntegerField(db_column='ref_id', default=0),
        ),
    ]
