# Generated by Django 5.2.9 on 2025-12-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatreference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_title_custom',
            field=models.BooleanField(db_column='is_title_custom', default=False),
        ),
    ]
