# Generated by Django 5.2.8 on 2025-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chat_is_title_custom"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMemory",
            fields=[
                (
                    "chat_sid",
                    models.AutoField(
                        db_column="chat_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "chat_room_id",
                    models.IntegerField(db_column="chat_room_id", db_index=True),
                ),
                ("user_id", models.CharField(db_column="user_id", max_length=60)),
                (
                    "case_type",
                    models.CharField(
                        db_column="case_type", db_index=True, max_length=50
                    ),
                ),
                (
                    "original_question",
                    models.TextField(
                        blank=True, db_column="original_question", null=True
                    ),
                ),
                (
                    "full_response",
                    models.TextField(blank=True, db_column="full_response", null=True),
                ),
                (
                    "summary",
                    models.TextField(blank=True, db_column="summary", null=True),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, db_column="topic", max_length=500, null=True
                    ),
                ),
                (
                    "referenced_memory_count",
                    models.IntegerField(db_column="referenced_memory_count", default=0),
                ),
                ("entities", models.JSONField(db_column="entities", default=list)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "verbose_name": "대화 메모리",
                "verbose_name_plural": "대화 메모리들",
                "db_table": "t_memory",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_room_id"], name="t_memory_chat_ro_495d3b_idx"
                    ),
                    models.Index(
                        fields=["case_type"], name="t_memory_case_ty_2d5d51_idx"
                    ),
                ],
            },
        ),
    ]
