# Generated by Django 5.2.8 on 2025-12-28 06:43

from django.db import migrations, models


def create_table_if_not_exists(apps, schema_editor):
    """테이블이 이미 존재하는 경우 건너뛰기"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 't_memory'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            # 테이블이 없으면 생성
            cursor.execute("""
                CREATE TABLE t_memory (
                    chat_sid SERIAL PRIMARY KEY,
                    chat_room_id INTEGER NOT NULL,
                    user_id VARCHAR(60) NOT NULL,
                    case_type VARCHAR(50) NOT NULL,
                    original_question TEXT,
                    full_response TEXT,
                    summary TEXT,
                    topic VARCHAR(500),
                    referenced_memory_count INTEGER NOT NULL DEFAULT 0,
                    entities JSONB NOT NULL DEFAULT '[]'::jsonb,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                );
            """)
            
            # 인덱스 생성
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS t_memory_chat_ro_495d3b_idx ON t_memory (chat_room_id);
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS t_memory_case_ty_2d5d51_idx ON t_memory (case_type);
            """)


def reverse_create_table(apps, schema_editor):
    """마이그레이션 롤백 시 테이블 삭제"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS t_memory CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chat_is_title_custom"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_table_if_not_exists,
                    reverse_create_table,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ConversationMemory",
                    fields=[
                        (
                            "chat_sid",
                            models.AutoField(
                                db_column="chat_sid", primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "chat_room_id",
                            models.IntegerField(db_column="chat_room_id", db_index=True),
                        ),
                        ("user_id", models.CharField(db_column="user_id", max_length=60)),
                        (
                            "case_type",
                            models.CharField(
                                db_column="case_type", db_index=True, max_length=50
                            ),
                        ),
                        (
                            "original_question",
                            models.TextField(
                                blank=True, db_column="original_question", null=True
                            ),
                        ),
                        (
                            "full_response",
                            models.TextField(blank=True, db_column="full_response", null=True),
                        ),
                        (
                            "summary",
                            models.TextField(blank=True, db_column="summary", null=True),
                        ),
                        (
                            "topic",
                            models.CharField(
                                blank=True, db_column="topic", max_length=500, null=True
                            ),
                        ),
                        (
                            "referenced_memory_count",
                            models.IntegerField(db_column="referenced_memory_count", default=0),
                        ),
                        ("entities", models.JSONField(db_column="entities", default=list)),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, db_column="created_at"),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, db_column="updated_at"),
                        ),
                    ],
                    options={
                        "verbose_name": "대화 메모리",
                        "verbose_name_plural": "대화 메모리들",
                        "db_table": "t_memory",
                        "ordering": ["-created_at"],
                        "indexes": [
                            models.Index(
                                fields=["chat_room_id"], name="t_memory_chat_ro_495d3b_idx"
                            ),
                            models.Index(
                                fields=["case_type"], name="t_memory_case_ty_2d5d51_idx"
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]
