# Generated by Django 5.2.9 on 2026-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversationmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunpodJob',
            fields=[
                ('url', models.URLField(db_column='url', max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zs_runpod',
            },
        ),
    ]
