# Generated by Django 5.2.8 on 2026-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatmessage_image_analysis_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessagefeedback",
            name="feedback_comment",
            field=models.TextField(
                blank=True,
                db_column="feedback_comment",
                help_text="싫어요 선택 시 추가 코멘트 (기타 사유)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessagefeedback",
            name="feedback_reason",
            field=models.CharField(
                blank=True,
                db_column="feedback_reason",
                help_text="싫어요 선택 시 사용자 피드백 사유 코드",
                max_length=50,
                null=True,
            ),
        ),
    ]
