version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: vectorDB
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: sknfinalproject
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
