version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pmc
    environment:
      POSTGRES_USER: pmc
      POSTGRES_PASSWORD: pmc1234
      POSTGRES_DB: pmc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pmd.sql:/docker-entrypoint-initdb.d/pmc.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview_user -d interview_chunking_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
