# Generated by Django 5.2.8 on 2025-12-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "note_sid",
                    models.AutoField(
                        db_column="note_sid", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=500)),
                (
                    "content",
                    models.TextField(blank=True, db_column="content", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("E", "사용"), ("D", "Disabled"), ("R", "Removed")],
                        db_column="status",
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
            ],
            options={
                "verbose_name": "노트",
                "verbose_name_plural": "노트들",
                "db_table": "t_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteAttachment",
            fields=[
                (
                    "attachment_sid",
                    models.AutoField(
                        db_column="attachment_sid", primary_key=True, serialize=False
                    ),
                ),
                ("file_name", models.CharField(db_column="file_name", max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, db_column="file_size", null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, db_column="file_type", max_length=50, null=True
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, db_column="file_path", max_length=1000, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
                (
                    "note",
                    models.ForeignKey(
                        db_column="note_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 첨부 파일",
                "verbose_name_plural": "노트 첨부 파일들",
                "db_table": "t_note_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteComment",
            fields=[
                (
                    "comment_sid",
                    models.AutoField(
                        db_column="comment_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "highlighted_text",
                    models.CharField(
                        blank=True,
                        db_column="highlighted_text",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("comment_text", models.TextField(db_column="comment_text")),
                (
                    "position_top",
                    models.SmallIntegerField(db_column="position_top", default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
                (
                    "note",
                    models.ForeignKey(
                        db_column="note_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 댓글",
                "verbose_name_plural": "노트 댓글들",
                "db_table": "t_note_comment",
                "ordering": ["position_top", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_column="user_id", max_length=60)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "note",
                    models.ForeignKey(
                        db_column="note_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 공유",
                "verbose_name_plural": "노트 공유들",
                "db_table": "t_note_share",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["note", "user_id"],
                        name="t_note_shar_note_si_c7545c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                (
                    "note_tag_sid",
                    models.AutoField(
                        db_column="note_tag_sid", primary_key=True, serialize=False
                    ),
                ),
                ("tag_name", models.CharField(db_column="tag_name", max_length=100)),
                (
                    "sort_order",
                    models.SmallIntegerField(db_column="sort_order", default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "note",
                    models.ForeignKey(
                        db_column="note_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "노트 태그",
                "verbose_name_plural": "노트 태그들",
                "db_table": "t_note_tag",
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["note", "tag_name"],
                        name="t_note_tag_note_si_41841f_idx",
                    )
                ],
                "unique_together": {("note", "tag_name")},
            },
        ),
    ]
