"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from config.env import env

import os
from rest_framework.authentication import SessionAuthentication

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])


# Application definition

INSTALLED_APPS = [
    # django_app/apps 내부의 앱을 INSTALLED_APPS에 등록
    "apps.account.apps.AccountConfig",
    "apps.experiments.apps.ExperimentsConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.chat.apps.ChatConfig",
    "apps.notes.apps.NotesConfig",
    "apps.schedule.apps.ScheduleConfig",
    "apps.navigation.apps.NavigationConfig",
    "apps.organization.apps.OrganizationConfig",
    "apps.codes.apps.CodesConfig",
    "apps.bookmark.apps.BookmarkConfig",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Swagger/OpenAPI
    "rest_framework",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 정적 파일 서빙 (SecurityMiddleware 바로 다음)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.account.middleware.DatabasePerformanceMiddleware",  # DB 성능 모니터링 (디버깅용)
    "apps.account.middleware.UserActivityLoggingMiddleware",
    "apps.account.middleware.SessionTimeoutMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.dashboard.context_processors.header_user",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("POSTGRES_DB"),
        'USER': env("POSTGRES_USER"),
        'PASSWORD': env("POSTGRES_PASSWORD"),
        'HOST': env("POSTGRES_HOST"),
        'PORT': env("POSTGRES_PORT"),
        # 연결 풀링 설정
        # CONN_MAX_AGE: 연결을 재사용할 시간(초)
        # 0 (기본값): 각 요청마다 새로운 연결을 만들고 닫음 (느림)
        # None: 연결을 영구적으로 유지 (권장하지 않음 - 연결 누수 위험)
        # 양수: 해당 시간 동안 연결을 재사용 (권장: 300-600초)
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=600),  # 10분
        # 연결 옵션 (psycopg 연결 파라미터)
        'OPTIONS': {
            # 연결 타임아웃 (초) - 너무 짧으면 느린 네트워크에서 실패
            'connect_timeout': env.int('DB_CONNECT_TIMEOUT', default=10),
            # 연결 유지 옵션 (TCP keepalive)
            'keepalives': 1,
            'keepalives_idle': 600,  # 10분
            'keepalives_interval': 30,  # 30초마다 확인
            'keepalives_count': 3,  # 3회 실패 시 연결 종료
            # 연결 풀링 관련 (psycopg v3용)
            # 'application_name': 'django_app',  # DB에서 확인 가능한 앱 이름
        },
        # 트랜잭션 자동 commit (롤백 메시지 감소)
        'ATOMIC_REQUESTS': False,  # False 권장 (성능상 이점)
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = "static/"
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'      # collectstatic 할 때 사용
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]
SASS_PROCESSOR_ROOT = BASE_DIR / 'static'

# WhiteNoise 설정 (정적 파일 서빙 및 압축)
# CompressedStaticFilesStorage: 압축만 수행 (파일명 해시 없음, CSS 내 상대 경로 참조 호환)
# CompressedManifestStaticFilesStorage: 압축 + 파일명 해시 (캐싱 최적화, CSS 내 경로 참조 시 문제 가능)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'uploads'

# File upload settings
# 1GB 파일 업로드 지원을 위한 설정
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB (기본값: 2.5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB (기본값: 2.5MB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 최대 필드 수 (기본값: 1000)

# 인증 관련 설정
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'
AUTH_USER_MODEL = 'account.CustomUser'

# 기본 세션 만료 설정
SESSION_COOKIE_AGE = 60 * 60  # 기본 세션 쿠키 만료 (1시간)
SESSION_SAVE_EVERY_REQUEST = False
SESSION_REFRESH_SECONDS = 60 * 60  # 활동 시마다 연장할 시간
SESSION_MAX_IDLE_SECONDS = 3 * 60 * 60  # 최대 무활동 허용 시간

# # 테스트(예: 10초 후 만료, 5초마다 연장) 시 아래 값으로 임시 대체
# SESSION_COOKIE_AGE = 10
# SESSION_REFRESH_SECONDS = 5
# SESSION_MAX_IDLE_SECONDS = 10


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
CHAT_USE_FAKE_COMPILE = env.bool("CHAT_USE_FAKE_COMPILE", default=False)
X_FRAME_OPTIONS = "SAMEORIGIN"

## SMTP
# EMAIL_BACKEND = env("EMAIL_BACKEND")
# EMAIL_HOST = env("EMAIL_HOST")
# EMAIL_PORT = env.int("EMAIL_PORT")
# EMAIL_HOST_USER = env("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL")
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
# DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")


# ───────────────────────────────────
# Google OAuth / Calendar
# ───────────────────────────────────
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")

# 용도별 리디렉션 URI
GOOGLE_REDIRECT_URIS = {
    'calendar': os.getenv("GOOGLE_CALENDAR_REDIRECT_URI", "http://localhost:8000/schedule/google/oauth2/callback/"),
    'profile': os.getenv("GOOGLE_PROFILE_REDIRECT_URI", "http://localhost:8000/accounts/google/login/callback/"),
}

# 기존 호환성 유지
GOOGLE_REDIRECT_URI = GOOGLE_REDIRECT_URIS.get('calendar', os.getenv("GOOGLE_REDIRECT_URI", ""))

GOOGLE_CALENDAR_SCOPE = os.getenv(
    "GOOGLE_CALENDAR_SCOPE",
    "https://www.googleapis.com/auth/calendar",
)

# ───────────────────────────────────
# REST Framework & Swagger/OpenAPI
# ───────────────────────────────────
# DRF SessionAuthentication에서 CSRF 우회를 위한 커스텀 인증 클래스
class CsrfExemptSessionAuthentication(SessionAuthentication):
    def enforce_csrf(self, request):
        # API 경로에서는 CSRF 검증을 우회
        if request.path.startswith('/api/'):
            return
        return super().enforce_csrf(request)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.settings.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'HelixOps AI Platform API',
    'DESCRIPTION': 'HelixOps AI Platform API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Swagger UI 설정
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 1,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
        # 세션 쿠키 자동 전달
        'withCredentials': True,
    },
    # 세션 인증을 위한 설정
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'sessionAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Django session cookie. 로그인 후 브라우저가 자동으로 전달합니다. Swagger UI에서 테스트하려면 먼저 로그인하세요.',
            },
            'csrftoken': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'csrftoken',
                'description': 'CSRF 토큰. 세션 인증과 함께 자동으로 전달됩니다.',
            }
        }
    },
    'SECURITY': [
        {'sessionAuth': []},
        {'csrftoken': []},
    ],
}
