"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from config.env import env

import os
from rest_framework.authentication import SessionAuthentication

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])


# Application definition

INSTALLED_APPS = [
    # django_app/apps 내부의 앱을 INSTALLED_APPS에 등록
    "apps.account.apps.AccountConfig",
    "apps.experiments.apps.ExperimentsConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.chat.apps.ChatConfig",
    "apps.notes.apps.NotesConfig",
    "apps.schedule.apps.ScheduleConfig",
    "apps.navigation.apps.NavigationConfig",
    "apps.organization.apps.OrganizationConfig",
    "apps.codes.apps.CodesConfig",
    "apps.bookmark.apps.BookmarkConfig",
    "apps.feedback.apps.FeedbackConfig",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Swagger/OpenAPI
    "rest_framework",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 정적 파일 서빙 (SecurityMiddleware 바로 다음)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.account.middleware.DatabasePerformanceMiddleware",  # DB 성능 모니터링 (디버깅용)
    "apps.account.middleware.UserActivityLoggingMiddleware",
    "apps.account.middleware.SessionTimeoutMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.dashboard.context_processors.header_user",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("POSTGRES_DB"),
        'USER': env("POSTGRES_USER"),
        'PASSWORD': env("POSTGRES_PASSWORD"),
        'HOST': env("POSTGRES_HOST"),
        'PORT': env("POSTGRES_PORT"),
        # 연결 풀링 설정
        # CONN_MAX_AGE: 연결을 재사용할 시간(초)
        # 0 (기본값): 각 요청마다 새로운 연결을 만들고 닫음 (느림)
        # None: 연결을 영구적으로 유지 (권장하지 않음 - 연결 누수 위험)
        # 양수: 해당 시간 동안 연결을 재사용 (권장: 300-600초)
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=600),  # 10분
        # 연결 옵션 (psycopg 연결 파라미터)
        'OPTIONS': {
            # 연결 타임아웃 (초) - 너무 짧으면 느린 네트워크에서 실패
            'connect_timeout': env.int('DB_CONNECT_TIMEOUT', default=10),
            # 연결 유지 옵션 (TCP keepalive)
            'keepalives': 1,
            'keepalives_idle': 600,  # 10분
            'keepalives_interval': 30,  # 30초마다 확인
            'keepalives_count': 3,  # 3회 실패 시 연결 종료
            # 연결 풀링 관련 (psycopg v3용)
            # 'application_name': 'django_app',  # DB에서 확인 가능한 앱 이름
        },
        # 트랜잭션 자동 commit (롤백 메시지 감소)
        'ATOMIC_REQUESTS': False,  # False 권장 (성능상 이점)
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = "static/"
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'      # collectstatic 할 때 사용
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]
SASS_PROCESSOR_ROOT = BASE_DIR / 'static'

# WhiteNoise 설정 (정적 파일 서빙 및 압축)
# CompressedStaticFilesStorage: 압축만 수행 (파일명 해시 없음, CSS 내 상대 경로 참조 호환)
# CompressedManifestStaticFilesStorage: 압축 + 파일명 해시 (캐싱 최적화, CSS 내 경로 참조 시 문제 가능)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'uploads'

# File upload settings
# 1GB 파일 업로드 지원을 위한 설정
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB (기본값: 2.5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB (기본값: 2.5MB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 최대 필드 수 (기본값: 1000)

# 인증 관련 설정
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'
AUTH_USER_MODEL = 'account.CustomUser'

# 기본 세션 만료 설정
SESSION_COOKIE_AGE = 60 * 60  # 기본 세션 쿠키 만료 (1시간)
SESSION_SAVE_EVERY_REQUEST = False
SESSION_REFRESH_SECONDS = 60 * 60  # 활동 시마다 연장할 시간
SESSION_MAX_IDLE_SECONDS = 3 * 60 * 60  # 최대 무활동 허용 시간

# # 테스트(예: 10초 후 만료, 5초마다 연장) 시 아래 값으로 임시 대체
# SESSION_COOKIE_AGE = 10
# SESSION_REFRESH_SECONDS = 5
# SESSION_MAX_IDLE_SECONDS = 10


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
CHAT_USE_FAKE_COMPILE = env.bool("CHAT_USE_FAKE_COMPILE", default=False)
X_FRAME_OPTIONS = "SAMEORIGIN"

## SMTP
# EMAIL_BACKEND = env("EMAIL_BACKEND")
# EMAIL_HOST = env("EMAIL_HOST")
# EMAIL_PORT = env.int("EMAIL_PORT")
# EMAIL_HOST_USER = env("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL")
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
# DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")


# ───────────────────────────────────
# Google OAuth / Calendar
# ───────────────────────────────────

# EC2 환경 감지 및 Parameter Store 헬퍼 함수
def is_ec2_instance():
    """EC2 인스턴스인지 확인"""
    try:
        import urllib.request
        urllib.request.urlopen("http://169.254.169.254/latest/meta-data/instance-id", timeout=1)
        return True
    except:
        return False

def _get_parameter_from_store(parameter_path: str, with_decryption: bool = False) -> str | None:
    """
    AWS Parameter Store에서 파라미터 값을 가져온다.
    
    Args:
        parameter_path: Parameter Store 경로
        with_decryption: SecureString 타입인 경우 복호화 여부
    
    Returns:
        파라미터 값, 실패 시 None
    """
    try:
        import boto3
        from botocore.exceptions import ClientError
    except ImportError:
        return None
    
    try:
        region = os.getenv("AWS_REGION", os.getenv("AWS_DEFAULT_REGION", "ap-northeast-2"))
        ssm_client = boto3.client("ssm", region_name=region)
        response = ssm_client.get_parameter(
            Name=parameter_path,
            WithDecryption=with_decryption
        )
        return response["Parameter"]["Value"]
    except (ClientError, Exception):
        return None

def _get_google_config(env_var_name: str, parameter_path: str, default: str = "", with_decryption: bool = False) -> str:
    """
    환경 변수 또는 Parameter Store에서 Google OAuth 설정 값을 가져온다.
    
    우선순위:
        1. 환경 변수
        2. Parameter Store (EC2 환경인 경우)
        3. 기본값
    
    Args:
        env_var_name: 환경 변수 이름
        parameter_path: Parameter Store 경로
        default: 기본값
        with_decryption: SecureString 타입인 경우 복호화 여부
    
    Returns:
        설정 값
    """
    # 1. 환경 변수 확인 (로컬 및 EC2 모두)
    value = os.getenv(env_var_name)
    if value:
        return value
    
    # 2. EC2 환경인 경우 Parameter Store에서 가져오기
    if is_ec2_instance():
        param_value = _get_parameter_from_store(parameter_path, with_decryption=with_decryption)
        if param_value:
            return param_value
    
    # 3. 기본값 반환
    return default

# Google OAuth 설정 (로컬: 환경변수, EC2: Parameter Store)
GOOGLE_CLIENT_ID = _get_google_config(
    "GOOGLE_CLIENT_ID",
    "/skn18/google-client-id",
    ""
)

GOOGLE_CLIENT_SECRET = _get_google_config(
    "GOOGLE_CLIENT_SECRET",
    "/skn18/google-client-secret",
    "",
    with_decryption=True  # 비밀번호는 SecureString으로 저장
)

# Google OAuth 설정 검증 (디버깅용)
if not GOOGLE_CLIENT_ID:
    import warnings
    warnings.warn(
        "GOOGLE_CLIENT_ID가 설정되지 않았습니다. "
        "Google 로그인 기능이 작동하지 않습니다. "
        "로컬 환경: GOOGLE_CLIENT_ID 환경 변수를 설정하세요. "
        "EC2 환경: Parameter Store의 /skn18/google-client-id를 확인하세요."
    )

# 용도별 리디렉션 URI
GOOGLE_REDIRECT_URIS = {
    'calendar': _get_google_config(
        "GOOGLE_CALENDAR_REDIRECT_URI",
        "/skn18/google-calendar-redirect-uri",
        "http://localhost:8000/schedule/google/oauth2/callback/"
    ),
    'profile': _get_google_config(
        "GOOGLE_PROFILE_REDIRECT_URI",
        "/skn18/google-profile-redirect-uri",
        "http://localhost:8000/accounts/google/login/callback/"
    ),
}

# 기존 호환성 유지
GOOGLE_REDIRECT_URI = GOOGLE_REDIRECT_URIS.get('calendar', _get_google_config("GOOGLE_REDIRECT_URI", "/skn18/google-redirect-uri", ""))

GOOGLE_CALENDAR_SCOPE = _get_google_config(
    "GOOGLE_CALENDAR_SCOPE",
    "/skn18/google-calendar-scope",
    "https://www.googleapis.com/auth/calendar"
)

# ───────────────────────────────────
# REST Framework & Swagger/OpenAPI
# ───────────────────────────────────
# DRF SessionAuthentication에서 CSRF 우회를 위한 커스텀 인증 클래스
class CsrfExemptSessionAuthentication(SessionAuthentication):
    def enforce_csrf(self, request):
        # API 경로에서는 CSRF 검증을 우회
        if request.path.startswith('/api/'):
            return
        return super().enforce_csrf(request)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.settings.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'HelixOps AI Platform API',
    'DESCRIPTION': 'HelixOps AI Platform API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Swagger UI 설정
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 1,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
        # 세션 쿠키 자동 전달
        'withCredentials': True,
    },
    # 세션 인증을 위한 설정
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'sessionAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Django session cookie. 로그인 후 브라우저가 자동으로 전달합니다. Swagger UI에서 테스트하려면 먼저 로그인하세요.',
            },
            'csrftoken': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'csrftoken',
                'description': 'CSRF 토큰. 세션 인증과 함께 자동으로 전달됩니다.',
            }
        }
    },
    'SECURITY': [
        {'sessionAuth': []},
        {'csrftoken': []},
    ],
}

# ───────────────────────────────────
# Logging Configuration
# ───────────────────────────────────
# AWS 배포 환경 고려사항:
# - docker-compose.prod.yml에서 CloudWatch Logs (awslogs driver) 사용
# - 프로덕션에서는 콘솔 로깅만 사용 (CloudWatch가 자동 수집)
# - 로컬 개발 환경에서는 파일 로깅도 사용 가능
# - 환경변수 DJANGO_LOG_TO_FILE=true로 파일 로깅 활성화 가능

# 로그 레벨 설정 (환경변수로 제어 가능)
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()
# 파일 로깅 활성화 여부 (기본값: DEBUG 모드일 때만, 프로덕션에서는 False)
LOG_TO_FILE = env.bool('DJANGO_LOG_TO_FILE', default=DEBUG)

# 로그 핸들러 설정
handlers_config = {
    'console': {
        'level': LOG_LEVEL,
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}

# 파일 로깅 핸들러 (로컬 개발 환경 또는 명시적으로 활성화한 경우)
if LOG_TO_FILE:
    # 로그 디렉토리 생성 (예외 처리 포함)
    log_dir = BASE_DIR / 'logs'
    try:
        os.makedirs(log_dir, exist_ok=True)
    except (OSError, PermissionError) as e:
        # AWS 컨테이너 환경에서 권한 문제 시 파일 로깅 비활성화
        import warnings
        warnings.warn(f"로그 디렉토리 생성 실패: {e}. 파일 로깅을 비활성화합니다.")
        LOG_TO_FILE = False
    
    if LOG_TO_FILE:
        handlers_config['file'] = {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(log_dir / 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        }
        handlers_config['debug_file'] = {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(log_dir / 'debug.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
            'encoding': 'utf-8',
        }

# 루트 핸들러 설정 (프로덕션에서는 콘솔만, 개발 환경에서는 파일도 포함)
root_handlers = ['console']
if LOG_TO_FILE:
    root_handlers.append('file')

# 각 logger의 핸들러 설정
logger_handlers = ['console']
if LOG_TO_FILE:
    logger_handlers.append('file')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[%(levelname)s] %(message)s',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': handlers_config,
    'root': {
        'handlers': root_handlers,
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': logger_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': logger_handlers,
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['debug_file'] if LOG_TO_FILE else ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': logger_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'graph': {
            'handlers': logger_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# ───────────────────────────────────
# Celery Configuration
# ───────────────────────────────────
# Celery를 사용하려면 celery 패키지를 설치해야 합니다: pip install celery
# 프로젝트에 이미 RabbitMQ가 설정되어 있으므로 RabbitMQ를 사용합니다.

# Celery Broker URL (메시지 브로커)
# RabbitMQ를 사용 (환경변수에서 직접 구성)
# 서버 환경: 환경변수에서 RABBITMQ_HOST, RABBITMQ_PORT, RABBITMQ_USER, RABBITMQ_PASSWORD 사용
# 로컬 환경: messaging/config.py에서 가져오거나 기본값 사용
try:
    from messaging.config import RABBITMQ_URL
    # messaging 모듈이 있으면 우선 사용 (로컬 개발 환경)
    CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=RABBITMQ_URL)
except ImportError:
    # messaging 모듈이 없으면 환경변수에서 직접 구성 (서버 환경)
    RABBITMQ_HOST = env('RABBITMQ_HOST')
    RABBITMQ_PORT = env('RABBITMQ_PORT')
    RABBITMQ_USER = env('RABBITMQ_USER')
    RABBITMQ_PASSWORD = env('RABBITMQ_PASSWORD')
    RABBITMQ_VHOST = env('RABBITMQ_VHOST')
    
    # URL 인코딩 (비밀번호와 vhost)
    from urllib.parse import quote_plus
    encoded_password = quote_plus(RABBITMQ_PASSWORD)
    encoded_vhost = quote_plus(RABBITMQ_VHOST)
    
    # RabbitMQ URL 구성
    DEFAULT_RABBITMQ_URL = f'amqp://{RABBITMQ_USER}:{encoded_password}@{RABBITMQ_HOST}:{RABBITMQ_PORT}/{encoded_vhost}'
    CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=DEFAULT_RABBITMQ_URL)

# Celery Result Backend (작업 결과 저장소)
# 최신 Celery는 RabbitMQ를 Result Backend로 직접 사용할 수 없습니다.
# 알림 생성은 결과를 저장할 필요가 없으므로 None으로 설정합니다.
# 결과가 필요한 경우 Django DB를 사용: 'db+postgresql://...' 또는 Redis 사용
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=None)

# Celery 시간대 설정
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_ENABLE_UTC = True

# Celery Beat 스케줄 설정 (주기적 작업)
# crontab을 사용하려면 아래 주석을 해제하고 위의 schedule을 주석 처리하세요
try:
    from celery.schedules import crontab
    
    CELERY_BEAT_SCHEDULE = {
        'check-schedule-reminders': {
            'task': 'apps.dashboard.tasks.check_schedule_reminders',
            # 방법 1: 초 단위로 지정 (5분 = 300초)
            'schedule': 300.0,
            # 방법 2: crontab 사용 (매 5분마다)
            # 'schedule': crontab(minute='*/5'),
            # 방법 3: 특정 시간에 실행 (매일 오전 9시)
            # 'schedule': crontab(hour=9, minute=0),
        },
    }
except ImportError:
    # celery가 설치되어 있지 않으면 기본 스케줄만 설정
    CELERY_BEAT_SCHEDULE = {
        'check-schedule-reminders': {
            'task': 'apps.dashboard.tasks.check_schedule_reminders',
            'schedule': 300.0,  # 5분마다 실행
        },
    }

# Celery 작업 설정
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30분
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25분

# 알림 시스템 설정
# 비동기 알림 사용 여부 (Celery를 통한 비동기 처리)
# 기본값: True (비동기 알림 활성화)
# False로 설정하려면 환경변수 NOTIFICATION_USE_ASYNC=False 설정
NOTIFICATION_USE_ASYNC = env.bool('NOTIFICATION_USE_ASYNC', default=True)
