# Generated by Django 5.2.9 on 2026-01-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_sid', models.AutoField(db_column='notification_sid', primary_key=True, serialize=False, verbose_name='알림 ID')),
                ('user_id', models.CharField(db_column='user_id', max_length=60, verbose_name='사용자 ID')),
                ('notification_type', models.CharField(choices=[('E', '실험'), ('M', '미팅'), ('A', '분석'), ('S', '세미나'), ('N', '노트'), ('C', '채팅'), ('SYS', '시스템')], db_column='notification_type', max_length=50, verbose_name='알림 타입')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='제목')),
                ('message', models.TextField(db_column='message', verbose_name='메시지')),
                ('read_yn', models.CharField(choices=[('Y', '읽음'), ('N', '읽지 않음')], db_column='read_yn', default='N', max_length=1, verbose_name='읽음 여부')),
                ('related_sid', models.IntegerField(blank=True, db_column='related_sid', help_text='experiment_sid, schedule_sid, note_sid, chat_sid 등', null=True, verbose_name='관련 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'db_table': 't_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='t_notificat_user_id_45600e_idx'), models.Index(fields=['user_id', 'read_yn'], name='t_notificat_user_id_ecbfbe_idx')],
            },
        ),
    ]
