# Generated by Django 6.0 on 2025-12-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='t_schedule',
            fields=[
                ('schedule_sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('Field', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_schedule',
            },
        ),
        migrations.CreateModel(
            name='t_note',
            fields=[
                ('note_sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '실험 노트',
                'verbose_name_plural': '실험 노트 목록',
                'db_table': 't_note',
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='note_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.t_note')),
            ],
        ),
        migrations.CreateModel(
            name='t_note_comment',
            fields=[
                ('note_comment_sid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(db_column='note_sid', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.t_note')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.t_note_comment')),
            ],
            options={
                'db_table': 't_note_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='t_note_tag',
            fields=[
                ('note_tag_sid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(db_column='note_sid', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='notes.t_note')),
            ],
            options={
                'db_table': 't_note_tag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='t_schedule_notes',
            fields=[
                ('schedule_note_sid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_sid', models.ForeignKey(db_column='note_sid', on_delete=django.db.models.deletion.CASCADE, to='notes.t_note')),
                ('schedule', models.ForeignKey(db_column='schedule_sid', on_delete=django.db.models.deletion.CASCADE, to='notes.t_schedule')),
            ],
            options={
                'db_table': 't_schedule_notes',
            },
        ),
        migrations.CreateModel(
            name='t_note_share',
            fields=[
                ('note_share_sid', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View'), ('comment', 'Comment'), ('edit', 'Edit')], default='view', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_column='shared_at')),
                ('expires_at', models.DateTimeField(blank=True, db_column='expires_at', null=True)),
                ('note', models.ForeignKey(db_column='note_sid', on_delete=django.db.models.deletion.CASCADE, to='notes.t_note')),
                ('sharer', models.ForeignKey(db_column='sharer_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_note_share',
                'unique_together': {('note', 'sharer')},
            },
        ),
    ]
