# Generated by Django 6.0 on 2025-12-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='t_bookmark',
            fields=[
                ('bookmark_sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_bookmark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='t_bookmark_item',
            fields=[
                ('bookmark_item_sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('source_type', models.CharField(choices=[('paper', 'Paper'), ('web', 'Web'), ('tool', 'Tool')], max_length=5)),
                ('source_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.CharField(max_length=255)),
                ('bookmark', models.ForeignKey(db_column='bookmark_sid', on_delete=django.db.models.deletion.CASCADE, to='bookmarks.t_bookmark')),
            ],
            options={
                'db_table': 't_bookmark_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='t_bookmark_item_notes',
            fields=[
                ('bookmark_item_note_sid', models.AutoField(primary_key=True, serialize=False)),
                ('excerpt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(db_column='bookmark_sid', on_delete=django.db.models.deletion.CASCADE, to='bookmarks.t_bookmark')),
                ('bookmark_item', models.ForeignKey(db_column='bookmark_item_sid', on_delete=django.db.models.deletion.CASCADE, to='bookmarks.t_bookmark_item')),
                ('note', models.ForeignKey(db_column='note_sid', on_delete=django.db.models.deletion.CASCADE, to='notes.t_note')),
            ],
            options={
                'db_table': 't_bookmark_item_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
