# Generated by Django 5.2.8 on 2026-01-03 12:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_sid', models.AutoField(db_column='organization_sid', primary_key=True, serialize=False)),
                ('organization_name', models.CharField(db_column='organization_name', max_length=255, verbose_name='조직 이름')),
                ('created_by_user_id', models.CharField(db_column='created_by_user_id', max_length=60, verbose_name='생성자 ID')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='수정일')),
            ],
            options={
                'verbose_name': '조직',
                'verbose_name_plural': '조직',
                'db_table': 'zs_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='초대 이메일')),
                ('invited_by_user_id', models.CharField(max_length=60, verbose_name='초대한 사용자 ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('expired', '만료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='초대일')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='수락일')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organization.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '조직 초대',
                'verbose_name_plural': '조직 초대',
                'db_table': 'zs_organization_invitation',
                'indexes': [models.Index(fields=['organization', 'email'], name='zs_organiza_organiz_6a95ba_idx'), models.Index(fields=['email', 'status'], name='zs_organiza_email_9ab5a6_idx')],
                'unique_together': {('organization', 'email', 'status')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='user_id', max_length=60, verbose_name='사용자 ID')),
                ('role', models.CharField(choices=[('owner', '소유자'), ('member', '멤버'), ('admin', '관리자')], db_column='role', default='member', max_length=50, verbose_name='역할')),
                ('joined_at', models.DateTimeField(db_column='joined_at', default=django.utils.timezone.now, verbose_name='가입일')),
                ('organization', models.ForeignKey(db_column='organization_sid', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '조직 멤버',
                'verbose_name_plural': '조직 멤버',
                'db_table': 'zs_organization_member',
                'indexes': [models.Index(fields=['organization', 'user_id'], name='zs_organiza_organiz_cb16f1_idx')],
                'unique_together': {('organization', 'user_id')},
            },
        ),
    ]
