# Generated by Django 5.2.8 on 2026-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('A', '활성'), ('R', '삭제됨')], db_column='status', default='A', max_length=1, verbose_name='상태'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='zs_organiza_status_86b4ed_idx'),
        ),
    ]
