# Generated by Django 5.2.8 on 2026-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinvitation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['organization', 'email', 'status'], name='zs_organiza_organiz_c862d5_idx'),
        ),
    ]
