# Generated by Django 5.2.9 on 2026-01-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_initial_periodic_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
