# Generated by Django 5.2.8 on 2025-12-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleCalendar",
            fields=[
                (
                    "google_calendar_id",
                    models.AutoField(
                        db_column="google_calendar_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calendar_name",
                    models.CharField(db_column="calendar_name", max_length=255),
                ),
                (
                    "calendar_email",
                    models.CharField(
                        blank=True,
                        db_column="calendar_email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=50, null=True
                    ),
                ),
                (
                    "is_connected",
                    models.CharField(
                        db_column="is_connected", default="N", max_length=1
                    ),
                ),
                (
                    "is_selected",
                    models.SmallIntegerField(db_column="is_selected", default=0),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, db_column="access_token", max_length=500, null=True
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, db_column="refresh_token", max_length=500, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
            ],
            options={
                "verbose_name": "Google 캘린더",
                "verbose_name_plural": "Google 캘린더들",
                "db_table": "t_google_calendar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_sid",
                    models.AutoField(
                        db_column="schedule_sid", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("E", "실험"),
                            ("M", "미팅"),
                            ("A", "분석"),
                            ("S", "세미나"),
                        ],
                        db_column="schedule_type",
                        max_length=50,
                    ),
                ),
                (
                    "schedule_status",
                    models.CharField(
                        choices=[("E", "예정"), ("R", "진행중"), ("C", "완료")],
                        db_column="schedule_status",
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "use_yn",
                    models.CharField(db_column="use_yn", default="Y", max_length=1),
                ),
                ("start_date", models.DateTimeField(db_column="start_date")),
                ("end_date", models.DateTimeField(db_column="end_date")),
                (
                    "is_all_day",
                    models.CharField(db_column="is_all_day", default="N", max_length=1),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="location", max_length=255, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=50, null=True
                    ),
                ),
                (
                    "linked_note_sid",
                    models.IntegerField(
                        blank=True, db_column="linked_note_sid", null=True
                    ),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("N", "반복 안 함"),
                            ("D", "매일"),
                            ("W", "매주"),
                            ("M", "매월"),
                            ("Y", "매년"),
                        ],
                        db_column="repeat_type",
                        default="N",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정들",
                "db_table": "t_schedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCalendar",
            fields=[
                (
                    "calendar_sid",
                    models.AutoField(
                        db_column="calendar_sid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "calendar_name",
                    models.CharField(db_column="calendar_name", max_length=255),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=50, null=True
                    ),
                ),
                (
                    "is_visible",
                    models.SmallIntegerField(db_column="is_visible", default=1),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("updated_id", models.CharField(db_column="updated_id", max_length=60)),
            ],
            options={
                "verbose_name": "사용자 캘린더",
                "verbose_name_plural": "사용자 캘린더들",
                "db_table": "t_user_calendar",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleShare",
            fields=[
                (
                    "schedule_share_sid",
                    models.AutoField(
                        db_column="schedule_share_sid",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_column="user_id", max_length=60)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정 공유",
                "verbose_name_plural": "일정 공유들",
                "db_table": "t_schedule_share",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "user_id"],
                        name="t_schedule__schedul_31ad0f_idx",
                    )
                ],
            },
        ),
    ]
