# Generated by Django 5.2.9 on 2025-12-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(db_column="access_token")),
                (
                    "refresh_token",
                    models.TextField(blank=True, db_column="refresh_token", null=True),
                ),
                ("client_id", models.TextField(db_column="client_id")),
                ("client_secret", models.TextField(db_column="client_secret")),
                ("scopes", models.TextField(db_column="scopes")),
                ("expiry", models.DateTimeField(db_column="expiry")),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google 자격증명",
                "verbose_name_plural": "Google 자격증명들",
                "db_table": "t_google_credentials",
            },
        ),
        migrations.CreateModel(
            name="SyncedCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar_id",
                    models.CharField(db_column="calendar_id", max_length=255),
                ),
                ("summary", models.CharField(db_column="summary", max_length=255)),
                ("selected", models.BooleanField(db_column="selected", default=True)),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=20, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "연동 캘린더",
                "verbose_name_plural": "연동 캘린더들",
                "db_table": "t_synced_calendar",
                "unique_together": {("user", "calendar_id")},
            },
        ),
    ]
