# Generated by Django 5.2.9 on 2025-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_googlecredentials_syncedcalendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncedcalendar",
            name="color",
            field=models.CharField(blank=True, default="#3b82f6", max_length=20),
        ),
    ]
