# Generated by Django 5.2.9 on 2025-12-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_syncedcalendar_color"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleCalendar",
        ),
        migrations.AlterModelOptions(
            name="googlecredentials",
            options={},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="scheduleshare",
            options={},
        ),
        migrations.AlterModelOptions(
            name="syncedcalendar",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usercalendar",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="scheduleshare",
            name="t_schedule__schedul_31ad0f_idx",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="color",
            field=models.CharField(
                blank=True, db_column="color", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("N", "반복 안 함"),
                    ("D", "매일"),
                    ("W", "매주"),
                    ("M", "매월"),
                    ("Y", "매년"),
                ],
                db_column="repeat_type",
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[("E", "실험"), ("M", "미팅"), ("A", "분석"), ("S", "세미나")],
                db_column="schedule_type",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="syncedcalendar",
            name="color",
            field=models.CharField(
                blank=True, db_column="color", default="#3b82f6", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="usercalendar",
            name="color",
            field=models.CharField(
                blank=True, db_column="color", max_length=20, null=True
            ),
        ),
    ]
