# Generated by Django 5.2.8 on 2025-12-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_delete_googlecalendar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "일정",
                "verbose_name_plural": "일정들",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleshare",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "일정 공유",
                "verbose_name_plural": "일정 공유들",
            },
        ),
        migrations.AlterModelOptions(
            name="usercalendar",
            options={
                "ordering": ["sort_order", "created_at"],
                "verbose_name": "사용자 캘린더",
                "verbose_name_plural": "사용자 캘린더들",
            },
        ),
        migrations.AlterField(
            model_name="schedule",
            name="color",
            field=models.CharField(
                blank=True, db_column="color", max_length=50, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleshare",
            index=models.Index(
                fields=["schedule", "user_id"], name="t_schedule__schedul_31ad0f_idx"
            ),
        ),
    ]
