# Generated by hand to introduce GoogleSyncedEvent cache table
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_useractivitylog"),
        ("schedule", "0005_alter_schedule_options_alter_scheduleshare_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSyncedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_column="event_id", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="status", default="active", max_length=20
                    ),
                ),
                (
                    "etag",
                    models.CharField(
                        blank=True, db_column="etag", max_length=255, null=True
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, db_column="summary", max_length=255, null=True
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, db_column="raw_payload", null=True
                    ),
                ),
                (
                    "google_updated",
                    models.DateTimeField(
                        blank=True, db_column="google_updated", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        db_column="calendar_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_events",
                        to="schedule.syncedcalendar",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        db_column="schedule_sid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sync",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_synced_events",
                        to="account.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "t_google_synced_event",
            },
        ),
        migrations.AlterUniqueTogether(
            name="googlesyncedevent",
            unique_together={("user", "calendar", "event_id")},
        ),
    ]
