# Generated by Django 5.2.8 on 2026-01-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_schedule_calendar_usercalendar_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_shared_copy",
            field=models.BooleanField(db_column="is_shared_copy", default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="original_schedule",
            field=models.ForeignKey(
                blank=True,
                db_column="original_schedule_sid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_copies",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduleshare",
            name="accepted_at",
            field=models.DateTimeField(blank=True, db_column="accepted_at", null=True),
        ),
        migrations.AddField(
            model_name="scheduleshare",
            name="accepted_calendar",
            field=models.ForeignKey(
                blank=True,
                db_column="accepted_calendar_sid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_shares",
                to="schedule.usercalendar",
            ),
        ),
        migrations.AddField(
            model_name="scheduleshare",
            name="shared_schedule",
            field=models.ForeignKey(
                blank=True,
                db_column="shared_schedule_sid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_from",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduleshare",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("accepted", "수락됨"),
                    ("rejected", "거절됨"),
                ],
                db_column="status",
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleshare",
            index=models.Index(
                fields=["user_id", "status"], name="t_schedule__user_id_f99b22_idx"
            ),
        ),
    ]
