# Generated by Django 5.2.8 on 2026-01-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "schedule",
            "0009_schedule_is_shared_copy_schedule_original_schedule_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleInvitation",
            fields=[
                (
                    "invitation_sid",
                    models.AutoField(
                        db_column="invitation_sid", primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(db_column="user_id", max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("accepted", "수락됨"),
                            ("rejected", "거절됨"),
                        ],
                        db_column="status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, db_column="accepted_at", null=True
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, db_column="rejected_at", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("created_id", models.CharField(db_column="created_id", max_length=60)),
            ],
            options={
                "verbose_name": "일정 공유 초대",
                "verbose_name_plural": "일정 공유 초대들",
                "db_table": "t_schedule_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="scheduleshare",
            name="t_schedule__user_id_f99b22_idx",
        ),
        migrations.RemoveField(
            model_name="scheduleshare",
            name="accepted_at",
        ),
        migrations.RemoveField(
            model_name="scheduleshare",
            name="accepted_calendar",
        ),
        migrations.RemoveField(
            model_name="scheduleshare",
            name="status",
        ),
        migrations.AddIndex(
            model_name="scheduleshare",
            index=models.Index(
                fields=["user_id"], name="t_schedule__user_id_142cf1_idx"
            ),
        ),
        migrations.AddField(
            model_name="scheduleinvitation",
            name="accepted_calendar",
            field=models.ForeignKey(
                blank=True,
                db_column="accepted_calendar_sid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invitations",
                to="schedule.usercalendar",
            ),
        ),
        migrations.AddField(
            model_name="scheduleinvitation",
            name="schedule",
            field=models.ForeignKey(
                db_column="schedule_sid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduleinvitation",
            name="shared_schedule",
            field=models.ForeignKey(
                blank=True,
                db_column="shared_schedule_sid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_from_invitation",
                to="schedule.schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleinvitation",
            index=models.Index(
                fields=["schedule", "user_id"], name="t_schedule__schedul_621299_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleinvitation",
            index=models.Index(
                fields=["user_id", "status"], name="t_schedule__user_id_59186b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleinvitation",
            index=models.Index(fields=["status"], name="t_schedule__status_ab86c7_idx"),
        ),
    ]
