# Generated by Django 5.2.9 on 2025-12-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_sid', models.AutoField(db_column='bookmark_sid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=500)),
                ('bookmark_url', models.CharField(db_column='bookmark_url', max_length=1000)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_id', models.CharField(db_column='updated_id', max_length=60)),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크들',
                'db_table': 't_bookmark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkCategory',
            fields=[
                ('category_sid', models.AutoField(db_column='category_sid', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', max_length=255)),
                ('sort_order', models.IntegerField(db_column='sort_order', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_id', models.CharField(db_column='updated_id', max_length=60)),
            ],
            options={
                'verbose_name': '북마크 카테고리',
                'verbose_name_plural': '북마크 카테고리들',
                'db_table': 't_bookmark_category',
                'ordering': ['sort_order', 'category_sid'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_id', models.CharField(db_column='created_id', max_length=60)),
                ('bookmark', models.ForeignKey(db_column='bookmark_sid', on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_maps', to='bookmark.bookmark')),
                ('category', models.ForeignKey(db_column='category_sid', on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_maps', to='bookmark.bookmarkcategory')),
            ],
            options={
                'verbose_name': '북마크 카테고리 매핑',
                'verbose_name_plural': '북마크 카테고리 매핑들',
                'db_table': 't_bookmark_map',
                'unique_together': {('bookmark', 'category')},
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='categories',
            field=models.ManyToManyField(related_name='bookmarks', through='bookmark.BookmarkMap', to='bookmark.bookmarkcategory'),
        ),
    ]
