# Generated by Django 5.2.8 on 2025-12-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(db_column='status', default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='bookmarkcategory',
            name='status',
            field=models.CharField(db_column='status', default='E', max_length=1),
        ),
    ]
